= REST Implementations for Things Edge Microservice
SMARTRAC Technology Fletcher Inc <api@smartrac-group.com>
ifdef::env-github[:USER: SMARTRACTECHNOLOGY]
ifdef::env-github[:REPO: smartcosmos-edge-things]
ifdef::env-github[:BRANCH: master]

image::https://jenkins.smartcosmos.net/buildStatus/icon?job={USER}/{REPO}/{BRANCH}[Build Status, link=https://jenkins.smartcosmos.net/job/{USER}/job/{REPO}/job/{BRANCH}/]

The Things Edge service provides an API for conveniently performing CRUD operations
on Things and their associated Metadata in single operations. Things and Metadata
are elements of the SMART COSMOS core metaphor, and more information on these elements
can be found here:

* https://api.smartcosmos.net/microservices/smartcosmos-ext-things-rdao/index.html[Things]
* https://api.smartcosmos.net/microservices/smartcosmos-ext-metadata-rdao/index.html[Metadata]

=== A Note About Tenants, Users, Roles, and Authorities

SMART COSMOS Objects has been designed from the outset to support multi-tenancy.
A Tenant has one or more Users (a default user with the Admin Role is created as part
of any Tenant creation), and a User has one or more Roles. Each Role contains zero
or more Authorities, and these are the Authorities referred to below.

The SMART COSMOS DevKit creates two Roles by default: Admin and User. Both Roles
contain all of the authorities listed below; the difference between the two Roles
is that a User with the Admin Role can create and edit Users. More information on
these elements can be found here:

* https://api.smartcosmos.net/microservices/smartcosmos-edge-user-devkit/index.html[User Management]

The developer can customize Roles and Authorities as needed, but the Authorities
listed in the API documentation are absolutely required by any User to execute the
relevant CRUD operations.

=== API Documentation

For detailed information on the SMART COSMOS Metadata API, please consult the link:API.adoc[API document].

=== Next Steps

To learn more about SMART COSMOS, have a look at link:https://github.com/SMARTRACTECHNOLOGY/smartcosmos-devkit#smart-cosmos-getting-started-guide[SMART COSMOS Getting Started Guide].

== Copyright and License
Code and documentation copyright 2016 Smartrac Technology Fletcher, Inc.  Code released under link:LICENSE[Apache 2.0 License].
